=== BartlomiejGrabowski/SpatialAnalyserServer/SpatialAnalyserServer/src/client/conf/clientConf.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ClientConf (SHPDownloadDir, SHPDownloadDir, SplashImage, NamingContext, Interfaces, ImagesDir)>
<!ELEMENT SHPDownloadDir (FlushContent, Location)>
<!ELEMENT OSMDownloadDir (FlushContent, Location)>
<!ELEMENT ImagesDir (Location)>
<!ELEMENT IconsDir (Location)>
<!ELEMENT SplashImage (Location)>
<!ELEMENT NamingContext (ServerContext, ObjectContext)>
<!ELEMENT Interfaces (ShpDraw, SHP)>
<!ELEMENT ShpDraw (ID, Kind)>
<!ELEMENT SHP (ID, Kind)>

<!ELEMENT FlushContent (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
<!ELEMENT ServerContext (#PCDATA)>
<!ELEMENT ObjectContext (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Kind (#PCDATA)>

=== BartlomiejGrabowski/SpatialAnalyserServer/SpatialAnalyserServer/src/client/conf/clientConf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ClientConf SYSTEM "clientConf.dtd">

<ClientConf>
	<DownloadDir>
		<FlushContent>1</FlushContent>
		<Location>downloads</Location>
	</DownloadDir>
	<SplashImage>
		<Location>images/splash.jpg</Location>
	</SplashImage>
	<NamingContext>
		<ServerContext>Server</ServerContext>
		<ObjectContext>Context</ObjectContext>
	</NamingContext>
</ClientConf>
